### ISSUE TITLE
Fix symlinks and add parameter for rmail/agree tos for headless run

### ISSUE THREAD

**Issue by AlmightyFrog** [dockette/letsencrypt#1]
Hi,

two improvement points:
1. At my machine copied certs link to "../archive/$name" which of course is not there on my local machine but only in docker. Following i did change to fix it for me:

```
-  cp ${CERTIFICATES}/. /var/www/certs/ -R
+  cp ${CERTIFICATES}/. /var/www/certs/ -R -L
```
1. How about adding mail and/or agree tos to be able run it headless? See changes in full patch for getting idea.

```
@@ -10,6 +10,7 @@ DARRAYS=(${DOMAINS});
 NGINX_DOMAINS=${DOMAINS}
 LE_DOMAINS=("${DARRAYS[*]/#/-d }")
 CERTIFICATES=/etc/letsencrypt/live
+MAILADRESS="${EMAIL}"

 # Inform
 echo "Creating certificates for: $NGINX_DOMAINS"
@@ -23,12 +24,12 @@ service nginx start

 # Run LetsEncrypt
 echo "- start letsencrypt"
-${LE_BIN} certonly --webroot -w /var/www/acme-certs ${LE_DOMAINS}
+${LE_BIN} certonly --webroot -w /var/www/acme-certs ${LE_DOMAINS} --email ${MAILADRESS} --agree-tos

 # Copy created certs
 if [ -d ${CERTIFICATES} ] ; then
   echo "- copy certificates to /var/www/certs"
-  cp ${CERTIFICATES}/. /var/www/certs/ -R
+  cp ${CERTIFICATES}/. /var/www/certs/ -R -L
 else
   echo "- certificates folder $CERTIFICATES not found"
 fi
```

Regards greenfrog

**Comment by f3l1x** [comment]
@AlmightyFrog 

Thanks for ideas.

I was looking for a email and agree-tos options. But theres nothing at usage. I'll add it as soon as possible.

**Comment by AlmightyFrog** [comment]
Cool! :)
Please keep in mind to somehow check if email is left empty - i do not know how letsencrypt reacts to that. So maybe just check if it is empty to abort whole process or so.

Note besides: I have one dynamic dns domain which i did want to create. Problem is, that i don't get a cert for that third level domain anymore cause there are already "too many" certs registered for that second level domain. Point is, that then i get no cert at all.
I'm not sure, if it is worth it to make therefore each domain call separate to get a cert or just leave it like it is cause if it does not work you somehow will recognize it.

**Comment by f3l1x** [comment]
@AlmightyFrog Same by me. During testing this docker image I have run out of all atempts for domain.

There are some limits, but not forever.
https://community.letsencrypt.org/t/beta-program-announcements/1631
